### ISSUE TITLE
compile error when builing latest version

### ISSUE THREAD

**Issue by humarf** [medoc92/libupnpp#12]
Hi medoc,

I tried to update to latest git version. When compiling I receive an error. Could you please check that?

Here is the build log, runs fine until I get this:

`mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./libupnpp -DDEBUG -g -Wall -DDATADIR=\"/usr/local/share/libupnpp\" -DCONFIGDIR=\"/usr/local/etc\" -std=c++11 -std=c++11 -g -O2 -MT libupnpp/ixmlwrap.lo -MD -MP -MF libupnpp/.deps/ixmlwrap.Tpo -c libupnpp/ixmlwrap.cxx  -fPIC -DPIC -o libupnpp/.libs/ixmlwrap.o
make: *** No rule to make target 'libupnpp/log.cxx', needed by 'libupnpp/log.lo'.  Stop.`

There is also one warning when compiling:
`libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./libupnpp -DDEBUG -g -Wall -DDATADIR=\"/usr/local/share/libupnpp\" -DCONFIGDIR=\"/usr/local/etc\" -std=c++11 -std=c++11 -g -O2 -MT libupnpp/control/discovery.lo -MD -MP -MF libupnpp/control/.deps/discovery.Tpo -c libupnpp/control/discovery.cxx  -fPIC -DPIC -o libupnpp/control/.libs/discovery.o
libupnpp/control/discovery.cxx:53:15: warning: 'std::string UPnPClient::cluDiscoveryToStr(const Upnp_Discovery*)' defined but not used [-Wunused-function]
 static string cluDiscoveryToStr(const struct Upnp_Discovery *disco)`

Thanks a lot and best regards
humarf

**Comment by medoc92** [comment]
the log.cxx has changed name (it's named log.cpp now because I share it with other packages). I think that a make distclean and sh autogen.sh should fix the problem.

The discovery.cxx warning is totally harmless.

**Comment by humarf** [comment]
Hi,

This helped - thank you very much. Unfortunately now it stops when doing make install. Could you please have a look what's wrong here now?

`su -c "LANG=C;make install"
Passwort: 
make[1]: Entering directory '/home/mhunger/temp/git/libupnpp'
 /bin/mkdir -p '/usr/local/lib'
/bin/mkdir: cannot create directory '/usr/local/lib': File exists
Makefile:561: recipe for target 'install-libLTLIBRARIES' failed
make[1]: *** [install-libLTLIBRARIES] Error 1
make[1]: Leaving directory '/home/mhunger/temp/git/libupnpp'
Makefile:1090: recipe for target 'install-am' failed
make: *** [install-am] Error 2`

Thanks a lot for your help
humarf

**Comment by medoc92** [comment]
This is really weird, because mkdir -p does not normally fail if the directory exists (it just does nothing). The bizarre possibility I'm seeing would be that an element of the path (e.g. local or lib) would be a file or a symbolic link to something which does not exist.

**Comment by humarf** [comment]
Thanks for your advice. I do not understand why - this never was a problem before - but /usr/local/lib is a symbolic link to /usr/local/lib64 that did not exist. Funny since libupnpp was already installed with /usr/local prefix. Maybe a change in directory structure when running last system update.

Now it works.

Best regards
humarf
