### ISSUE TITLE
using multiple network interfaces

### ISSUE THREAD

**Issue by wdehoog** [medoc92/libupnpp#14]
Hi,

I have a question. 

While trying to use this library on my phone (Oneplus One with Sailfish) I ran into a problem. The renderer is running on the phone and the server on the wlan. It looks like getLibUPnP assumes only one interface is used while I need two simultaneously (lo and wlan0).

I this assumption true? How can I use libupnpp with multiple interfaces?

**Comment by medoc92** [comment]
Portable upnp, aka libupnp, which libupnpp uses to do the real work, can only use one interface (actually one IP address). By default, it chooses the first non loopback interface.  You can specify an interface or an address in the library initialization call getLibUPnP(). 

This does mean that libupnp can't work if the renderer and server it needs to talk to are actually on separate networks. In your case, I guess that the only possibility would be to have the renderer listen on the wlan. 

This is a quite ennoying limitation of pupnp, but it would be very difficult to change, the single interface idea is embedded deep in the lib (the IP is a global...).

This is rarely an issue in practise, but one of the recurring case is one of the entities being local.

**Comment by wdehoog** [comment]
Thanks for the explanation. Eventhough the problem remains I'll close the issue since there is not much that can be done.
