### ISSUE TITLE
xml entity encoding

### ISSUE THREAD

**Issue by wdehoog** [medoc92/libupnpp#15]
Hi,

While using libupnpp I could not get rygel to use the uri set by setNextAVTransportURI. The log of rygel showed:
  Entity: line 1: parser error : xmlParseEntityRef: no name
  </upnp:artist><upnp:album>Digital Nation - Mix CD</upnp:album><upnp:genre>Drum & 
so the didl was not correct xml ('&' should ave been '&amp;'). 

Can this be caused by libupnpp or does it only pass the didl received from the content server (minidlna in this case)? 

-edit-

With wireshark I see that minidlna sends:
raw:  
  lt;upnp:genre&amp;gt;Drum &amp;amp;amp; Bass&amp;lt;/upnp:genre&amp;gt;

unescaped: 
  &lt;upnp:genre&gt;Drum &amp;amp; Bass&lt;/upnp:genre&gt;

2nd time unescaped:
<upnp:genre>Drum &amp; Bass</upnp:genre>

**Comment by wdehoog** [comment]
Did more logging. libupnpp seems to act correct so my problem lies elsewhere. sorry.

**Comment by medoc92** [comment]
For the record, the general philosophy is for libupnpp to try to pass the Media Server info unmodified. But it's easy to get it wrong with the layers of XML escaping...
