### ISSUE TITLE
Compilation error: namespace 'std' does not name a template typ

### ISSUE THREAD

**Issue by tristelune1** [medoc92/libupnpp#18]
Hello,
I try to package the last version and I get the following error:

`libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./libupnpp -DDEBUG -g -Wall -pthread -I/usr/include/upnp -DDATADIR=\"/usr/share/libupnpp\" -DCONFIGDIR=\"/usr/etc\" -std=c++11 -std=c++11 -std=c++11 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -MT libupnpp/control/mediarenderer.lo -MD -MP -MF libupnpp/control/.deps/mediarenderer.Tpo -c libupnpp/control/mediarenderer.cxx  -fPIC -DPIC -o libupnpp/control/.libs/mediarenderer.o

In file included from ./libupnpp/control/avtransport.hxx:26:0,
                 from libupnpp/control/avtransport.cxx:18:
./libupnpp/control/service.hxx:65:6: error: 'function' in namespace 'std' does not name a template type
 std::function<void (const std::unordered_map<std::string, std::string>&)>
      ^~~~~~~~

./libupnpp/control/service.hxx:120:27: error: 'evtCBFunc' has not been declared
     void registerCallback(evtCBFunc c);
                           ^~~~~~~~~

libupnpp/control/avtransport.cxx:37:22: error: 'placeholders' is not a namespace-name
 using namespace std::placeholders;
`
Do I need to pass some flags to the compiler or there is an error somewhere else ? 

Thank you!

**Comment by medoc92** [comment]
Try adding an ```#include <functional>``` in service.hxx (around ```#include <vector>``` for example)

I think that it should be there, but for some reason, it has never been a problem on the platforms I build one.
