### ISSUE TITLE
Add support for AllStream and AirAudio.

### ISSUE THREAD

**Issue by Manuel4131** [medoc92/libupnpp#3]
These two app pushes music in LPCM/WAV format to the dmr. But only noises can be sound. What could the problem? I doubt it's the decoder of MPD. But as I use AirAurio, the M_CONN is 0. It's strange. Any suggestion?

**Comment by medoc92** [comment]
In my experience MPD before circa 1.19.4 has huge trouble playing uncompressed sound from an http stream. In addition, for reliable results with http wav, it should be configured without libaudiofile.

This is what I found while developping the sc2mpd songcast -> mpd gateway.
http://www.lesbonscomptes.com/upmpdcli/sc2mpd.html

The notes there mainly mention 24 bits sound, but there were quite a few misc problems with http streaming and everything except mp3 in the past. The safe approach: 1.19 + libsndfile, no libaudiofile

**Comment by medoc92** [comment]
Oh, and I don't know what M_CONN is ?

**Comment by Manuel4131** [comment]
The method bool MPDCli::play(int pos) in the file upmpdcli/src/mpdcli.cxx always return 0 as the AirAudio connects to it.

**Comment by medoc92** [comment]
Sorry, I have a lot of trouble understanding what you mean. What connects to what exactly ? Maybe it might help me understand what you are doing if you could post a repository with your modifications somewhere ?
