### ISSUE TITLE
How to add CDS Content Directory Service?

### ISSUE THREAD

**Issue by Manuel4131** [medoc92/libupnpp#4]
The server should face various clients by learning their ability so changing its' behavior. A profile is to define the formats which are used to transcode the data when a  media is not  supported by devices. So do you plan to create a CDS profile?

**Comment by medoc92** [comment]
Transcoding is usually a function of the Media Server. As there is currently no Media Server device code in libupnpp (only Control Point code), could you please be more specific about what you mean ?

**Comment by Manuel4131** [comment]
I mean can you add the media service part and related CDS content sample?

**Comment by medoc92** [comment]
Developping a media server is a lot of work, and there are already a number of free and good ones, so, no, I don't intend to develop CDS code, but I'll welcome patches if someone wants to do it !
