### ISSUE TITLE
Cross Compiling for Android

### ISSUE THREAD

**Issue by sk2212** [medoc92/libupnpp#5]
Hello,

is it possible to build this wrapper also for Android ARM platform?

I have already built "libupnp" library for Android from here "https://github.com/yixia/libupnp".

Best Regards

**Comment by medoc92** [comment]
Hi,

I see no reason why the wrapper could not be built on Android, but I never tried, so there might be issues. I am currently trying to port it to Windows (to see if I can get the control point working) by the way.

Also by the way, and about libupnp, the patches in https://github.com/medoc92/pupnp16 really make a difference, I had confirmation again this week that using them solved a "player disappearance" issue.

In any case, if you try to port libupnpp to Android, I'll gladly merge the changes needed, so go for it !

Cheers,

jf

**Comment by sk2212** [comment]
Okay...it seems to work. I was not able to cross compile libupnpp over configure and make but directly within QtCreator. Need also some special files for "getsyshdaddr.c " because of missing Android implementation.

However, can you give me some lines of code to test the library? Maybe just discovering?

UPnPClient::UPnPDeviceDirectory::getTheDir() should be perfom such a scan, shouldn`t it? Under Linux system there is some output on console from curl and so on. But when running on Android device I have no console output.

So I need something to get one entry of found devices. Is this possible?

I must say that my C++ knowlegdes are not very good because I came from the Java world.

Regards

**Comment by medoc92** [comment]
Here is a small example for listing the discovered devices. I guess that you'll have to change it to do something other than printing to stderr, but this should be reasonably simple:

http://pastebin.com/zKe9d3pk

Something like the following works for building it on Linux:

    c++ -std=c++0x -o uplistdir uplistdir.cpp -lupnpp

I come from the C++ world, but I'm not sure that my C++ knowledge is very good either, by the way :)
