### ISSUE TITLE
std::future is not available for ARMv5

### ISSUE THREAD

**Issue by joerg-krause** [medoc92/libupnpp#8]
Commit cebfb37a21394ec73c72b9f7c5a4b840798acdf1 breaks compilation for an ARMv5 soft-float target:

```
In file included from libupnpp/control/discovery.cxx:37:0:
./libupnpp/workqueue.h:308:29: error: field 'res' has incomplete type 'std::future<void*>'
         std::future<void *> res;
                             ^~~
In file included from ./libupnpp/workqueue.h:21:0,
                 from libupnpp/control/discovery.cxx:37:
/home/joerg/Development/hbm10/hbm10-next/toolchain/output/host/usr/arm-buildroot-linux-musleabi/include/c++/6.2.0/future:115:11: note: declaration of 'class std::future<void*>'
     class future;
           ^~~~~~
In file included from libupnpp/control/discovery.cxx:37:0:
./libupnpp/workqueue.h: In member function 'bool WorkQueue<T>::start(int, void* (*)(void*), void*)':
./libupnpp/workqueue.h:81:25: error: invalid use of incomplete type 'class std::packaged_task<void*(void*)>'
             w.res = task.get_future();
                         ^
In file included from ./libupnpp/workqueue.h:21:0,
                 from libupnpp/control/discovery.cxx:37:
/home/joerg/Development/hbm10/hbm10-next/toolchain/output/host/usr/arm-buildroot-linux-musleabi/include/c++/6.2.0/future:121:11: note: declaration of 'class std::packaged_task<void*(void*)>'
     class packaged_task;
           ^~~~~~~~~~~~~
In file included from libupnpp/control/discovery.cxx:37:0:
./libupnpp/workqueue.h: In instantiation of 'bool WorkQueue<T>::start(int, void* (*)(void*), void*) [with T = UPnPClient::DiscoveredTask*]':
libupnpp/control/discovery.cxx:333:51:   required from here
./libupnpp/workqueue.h:79:61: error: 'std::packaged_task<void*(void*)> task' has incomplete type
             std::packaged_task<void *(void *)> task(workproc);
                                                             ^
./libupnpp/workqueue.h:81:15: error: 'struct WorkQueue<UPnPClient::DiscoveredTask*>::Worker' has no member named 'res'
             w.res = task.get_future();
             ~~^~~
./libupnpp/workqueue.h: In instantiation of 'void* WorkQueue<T>::setTerminateAndWait() [with T = UPnPClient::DiscoveredTask*]':
libupnpp/control/discovery.cxx:388:41:   required from here
./libupnpp/workqueue.h:192:53: error: '__gnu_cxx::__alloc_traits<std::allocator<WorkQueue<UPnPClient::DiscoveredTask*>::Worker> >::value_type {aka struct WorkQueue<UPnPClient::DiscoveredTask*>::Worker}' has no member named 'res'
             void *status = m_worker_threads.front().res.get();
                                                      
libupnpp/control/discovery.cxx: At global scope:
libupnpp/control/discovery.cxx:53:15: warning: 'std::__cxx11::string UPnPClient::cluDiscoveryToStr(const Upnp_Discovery*)' defined but not used [-Wunused-function]
 static string cluDiscoveryToStr(const struct Upnp_Discovery *disco)
               ^~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:775: libupnpp/control/discovery.lo] Error 1
```

The problem is that is is not possible to use `std::future` for this target because libstdc++ only enables `std::future` if [`ATOMIC_INT_LOCK_FREE > 1`](https://github.com/gcc-mirror/gcc/blob/365ba13de381fc0ce6321ea9348c9c9972dd60d9/libstdc%2B%2B-v3/include/std/future#L185-L186) and for the ARMv5 target the cross-toolchain reports:

```
$ echo | /usr/bin/arm-linux-g++ -dM -E - | grep ATOMIC_INT_LOCK_FREE
#define __GCC_ATOMIC_INT_LOCK_FREE 1
```

There is a related [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=727621) on Debian about this issue.

I am not sure, what a proper solution is, but I really would like to have support for ARMv5 again.

**Comment by medoc92** [comment]
I think that this 'future' business is not used for much and could just be ifdefed out. Please try the patch, and I'll commit it if it builds. The lib does not actually use the value which is computed from the future, so no function is lost.


[no-future.zip](https://github.com/medoc92/libupnpp/files/465971/no-future.zip)

**Comment by joerg-krause** [comment]
Unfortunately, it does not compile as `packaged_task` is also part of `std::future`.

**Comment by medoc92** [comment]
Ok, we don't need packaged_task if we don't use future in fact...
Attaching a more complete patch

[no-future2.zip](https://github.com/medoc92/libupnpp/files/466124/no-future2.zip)

**Comment by joerg-krause** [comment]
Thanks! It does compile if I change the use of `std::thread`.

Instead of checking for `__GCC_ATOMIC_INT_LOCK_FREE` I would prefer to check for `std::future`. I will propose a PR request with your changes, if you don't mind.

**Comment by joerg-krause** [comment]
Note, that this issue is most probably fixed in https://github.com/gcc-mirror/gcc/commit/c45be7f1aef92f2ea7363cbc4627f943b83ca902. Originally std::future was only supported for targets with always-lock-free atomics for int, but now the check for `ATOMIC_INT_LOCK_FREE > 1` has been removed in `libstdc++-v3/include/std/future`.

**Comment by medoc92** [comment]
Thanks for the update !
